language: ruby
rvm:
 - 2.2.1

before_install:
  - sudo apt-get update
  - sudo apt-get install -y nodejs npm git
  - npm install
  - npm install -g grunt-cli
  - gem install bundler
  - bundle install
  - grunt
  - git config --global user.email "iblancasa@gmail.com"
  - git config --global user.name "Israel Blancas"
  - git clone -b gh-pages https://iblancasa:${GH_TOKEN}@github.com/iblancasa/blog.git _site
  - sudo rm -r _site/*
script:
  - bundle exec jekyll build
after_script:
  - grunt compress
  - cd _site/
  - git ls-files --deleted -z | xargs -0 git rm
  - echo "blog.iblancasa.com" > CNAME
  - git add *
  - git add .
  - git commit -m "`date`"
  - git push origin gh-pages --quiet
